[GLOBAL]
pants_version = "2.14.0"

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.bandit",
  "pants.backend.python.lint.isort",
  "pants.backend.python.lint.pylint",
  "pants.backend.python.lint.docformatter",
  "pants.backend.experimental.python.lint.pyupgrade",
  "pants.backend.python.lint.black",
  "pants.backend.plugin_development",
  "jupyter_book"
]

# path to pants plugins
pythonpath = ["%(buildroot)s/pants-plugins"]

[source]
root_patterns = [
  '/src',
  '/pants-plugins'
]

[python]
interpreter_constraints = ["CPython==3.11.*"]
enable_resolves = true

[python-bootstrap]
search_path = ["<ASDF_LOCAL>"]

[python.resolves]
pants-plugins = "3rdparty/python/pants_lock.txt"
python-default = "3rdparty/python/default_lock.txt"

[jupyter-book]
extra_requirements = ["sphinxcontrib-mermaid>=0.7.1", "pyppeteer>=1.0.2"]


[anonymous-telemetry]
enabled = true
repo_id = "4d11e8d0-8dd9-11ed-a86a-6045bdd664ae"
