[GLOBAL]
pants_version = "2.14.0"

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.bandit",
  "pants.backend.python.lint.isort",
  "pants.backend.python.lint.pylint",
  "pants.backend.python.lint.docformatter",
  "pants.backend.experimental.python.lint.pyupgrade",
  "pants.backend.python.lint.black",
]

[python]
enable_resolves = true

[python.resolves]
python-default = "default.lock"


[anonymous-telemetry]
enabled = true
repo_id = "4d11e8d0-8dd9-11ed-a86a-6045bdd664ae"
